top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/http
builddir     = /home/tyekx/work/webs/httpd/modules/http
VPATH        = /home/tyekx/work/webs/httpd/modules/http

include $(top_srcdir)/build/special.mk

