top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/apreq
builddir     = /home/tyekx/work/webs/httpd/modules/apreq
VPATH        = /home/tyekx/work/webs/httpd/modules/apreq
include $(top_srcdir)/build/special.mk
