top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/arch/unix
builddir     = /home/tyekx/work/webs/httpd/modules/arch/unix
VPATH        = /home/tyekx/work/webs/httpd/modules/arch/unix

include $(top_srcdir)/build/special.mk

