top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/server/mpm
builddir     = /home/tyekx/work/webs/httpd/server/mpm
VPATH        = /home/tyekx/work/webs/httpd/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
