top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/loggers
builddir     = /home/tyekx/work/webs/httpd/modules/loggers
VPATH        = /home/tyekx/work/webs/httpd/modules/loggers

include $(top_srcdir)/build/special.mk

