top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/generators
builddir     = /home/tyekx/work/webs/httpd/modules/generators
VPATH        = /home/tyekx/work/webs/httpd/modules/generators

include $(top_srcdir)/build/special.mk

