top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/mappers
builddir     = /home/tyekx/work/webs/httpd/modules/mappers
VPATH        = /home/tyekx/work/webs/httpd/modules/mappers

include $(top_srcdir)/build/special.mk

