top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/aaa
builddir     = /home/tyekx/work/webs/httpd/modules/aaa
VPATH        = /home/tyekx/work/webs/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

