top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/metadata
builddir     = /home/tyekx/work/webs/httpd/modules/metadata
VPATH        = /home/tyekx/work/webs/httpd/modules/metadata

include $(top_srcdir)/build/special.mk

