top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/echo
builddir     = /home/tyekx/work/webs/httpd/modules/echo
VPATH        = /home/tyekx/work/webs/httpd/modules/echo

include $(top_srcdir)/build/special.mk

