top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/os
builddir     = /home/tyekx/work/webs/httpd/os
VPATH        = /home/tyekx/work/webs/httpd/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
