top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/modules/filters
builddir     = /home/tyekx/work/webs/httpd/modules/filters
VPATH        = /home/tyekx/work/webs/httpd/modules/filters

include $(top_srcdir)/build/special.mk

