top_srcdir   = /home/tyekx/work/webs/httpd
top_builddir = /home/tyekx/work/webs/httpd
srcdir       = /home/tyekx/work/webs/httpd/server/mpm/event
builddir     = /home/tyekx/work/webs/httpd/server/mpm/event
VPATH        = /home/tyekx/work/webs/httpd/server/mpm/event
include $(top_srcdir)/build/special.mk
